In [3]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score


ames = pd.read_csv('/Users/avanti/OneDrive/MASTERS/GSB544-Computing and Machine Learning/Practice Activities/PA_7.1/AmesHousing.csv')

# Get rid of columns with mostly NaN values
good_cols = ames.isna().sum() < 100
ames = ames.loc[:,good_cols]

# Drop other NAs
ames = ames.dropna()

ames.head()

Order        PID  MS SubClass  ... Sale Type  Sale Condition SalePrice
0      1  526301100           20  ...       WD           Normal    215000
1      2  526350040           20  ...       WD           Normal    105000
2      3  526351010           20  ...       WD           Normal    172000
3      4  526353030           20  ...       WD           Normal    244000
4      5  527105010           60  ...       WD           Normal    189900

[5 rows x 70 columns]

In [4]:
lr = LinearRegression()

X = ames[["Gr Liv Area", "TotRms AbvGrd"]]
y = ames["SalePrice"]



X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train_s = (X_train - X_train.mean())/X_train.std()

lr_fitted = lr.fit(X_train_s, y_train)
lr_fitted.coef_

array([ 70400.99187538, -17847.48237565])

In [5]:
y_preds = lr_fitted.predict(X_test)

r2_score(y_test, y_preds)

-1939974.1688547109

In [6]:
y_preds[1:5]

array([1.21991150e+08, 1.55043921e+08, 1.28608843e+08, 8.11238685e+07])

In [7]:
new_house = pd.DataFrame(data = {"Gr Liv Area": [889], "TotRms AbvGrd": [6]})
new_house

Gr Liv Area  TotRms AbvGrd
0          889              6

In [8]:
new_house_s = (new_house - new_house.mean())/new_house.std()
new_house_s

Gr Liv Area  TotRms AbvGrd
0          NaN            NaN

In [9]:
X_test_s = (X_test - X_train.mean())/X_train.std()
y_preds = lr_fitted.predict(X_test_s)

r2_score(y_test, y_preds)

0.5132137299431012

In [10]:
new_house_s = (new_house - X_train.mean())/X_train.std()
lr_fitted.predict(new_house_s)

array([99211.46944644])

In [11]:
lr_pipeline = Pipeline(
  [("standardize", StandardScaler()),
  ("linear_regression", LinearRegression())]
)

lr_pipeline

Pipeline(steps=[('standardize', StandardScaler()),
                ('linear_regression', LinearRegression())])

In [12]:
lr_pipeline_fitted = lr_pipeline.fit(X_train, y_train)

y_preds = lr_pipeline_fitted.predict(X_test)
r2_score(y_test, y_preds)

0.5132137299431013

In [13]:
lr_pipeline_fitted.predict(new_house)

array([99211.46944644])

In [14]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
  [
    ("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
    ("standardize", StandardScaler(), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
)


lr_pipeline = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
)

lr_pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('dummify',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Bldg Type']),
                                                 ('standardize',
                                                  StandardScaler(),
                                                  ['Gr Liv Area',
                                                   'TotRms AbvGrd'])])),
                ('linear_regression', LinearRegression())])

In [15]:
X = ames.drop("SalePrice", axis = 1)
y = ames["SalePrice"]



X_train, X_test, y_train, y_test = train_test_split(X, y)

lr_fitted = lr_pipeline.fit(X_train, y_train)

In [16]:
ct_fitted = ct.fit(X_train)

ct.transform(X_train)

array([[ 1.        ,  0.        ,  0.        , ...,  0.        , -0.63916584,
        -0.26681461],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.5230414 ,
         0.36867289],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.8071365 ,
         0.36867289],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -1.58482506,
        -1.53778963],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.41377405,
        -0.26681461],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.08994537,
         0.36867289]])

In [17]:
ct.transform(X_test)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.00000000e+00, -1.72296266e-01, -2.66814613e-01],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  5.44810327e-04, -2.66814613e-01],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00, -5.61685357e-01, -2.66814613e-01],
       ...,
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  1.31665627e-01, -9.02302121e-01],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  6.72042325e-01,  3.68672895e-01],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00, -3.51097379e-01, -9.02302121e-01]])

In [18]:
lr_pipeline_fitted.named_steps['linear_regression'].coef_

array([ 70384.34664714, -17843.26261383])

In [19]:
type(y_preds)

numpy.ndarray

In [20]:
lr_pipeline = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
).set_output(transform="pandas")


ct.fit_transform(X_train)

dummify__Bldg Type_1Fam  ...  standardize__TotRms AbvGrd
1964                      1.0  ...                   -0.266815
2215                      1.0  ...                    0.368673
1540                      1.0  ...                    0.368673
960                       1.0  ...                    0.368673
2606                      1.0  ...                   -0.266815
...                       ...  ...                         ...
2562                      1.0  ...                   -0.902302
1834                      0.0  ...                   -0.266815
2206                      1.0  ...                   -1.537790
141                       1.0  ...                   -0.266815
1231                      1.0  ...                    0.368673

[2115 rows x 7 columns]

In [21]:
ct_inter = ColumnTransformer(
  [
    ("interaction", PolynomialFeatures(interaction_only = True), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
).set_output(transform = "pandas")

ct_inter.fit_transform(X_train)

interaction__1  ...  interaction__Gr Liv Area TotRms AbvGrd
1964             1.0  ...                                  7020.0
2215             1.0  ...                                 12285.0
1540             1.0  ...                                 13286.0
960              1.0  ...                                 11487.0
2606             1.0  ...                                  7944.0
...              ...  ...                                     ...
2562             1.0  ...                                  7890.0
1834             1.0  ...                                  8268.0
2206             1.0  ...                                  2776.0
141              1.0  ...                                 10200.0
1231             1.0  ...                                 10759.0

[2115 rows x 4 columns]

In [22]:
ct_dummies = ColumnTransformer(
  [("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"])],
  remainder = "passthrough"
).set_output(transform = "pandas")

ct_inter = ColumnTransformer(
  [
    ("interaction", PolynomialFeatures(interaction_only = True), ["remainder__TotRms AbvGrd", "dummify__Bldg Type_1Fam"]),
  ],
  remainder = "drop"
).set_output(transform = "pandas")

X_train_dummified = ct_dummies.fit_transform(X_train)
X_train_dummified

dummify__Bldg Type_1Fam  ...  remainder__Sale Condition
1964                      1.0  ...                     Normal
2215                      1.0  ...                     Normal
1540                      1.0  ...                     Normal
960                       1.0  ...                     Normal
2606                      1.0  ...                    Abnorml
...                       ...  ...                        ...
2562                      1.0  ...                     Normal
1834                      0.0  ...                     Normal
2206                      1.0  ...                     Normal
141                       1.0  ...                     Normal
1231                      1.0  ...                    Abnorml

[2115 rows x 73 columns]

In [23]:
ct_inter.fit_transform(X_train_dummified)

interaction__1  ...  interaction__remainder__TotRms AbvGrd dummify__Bldg Type_1Fam
1964             1.0  ...                                                6.0            
2215             1.0  ...                                                7.0            
1540             1.0  ...                                                7.0            
960              1.0  ...                                                7.0            
2606             1.0  ...                                                6.0            
...              ...  ...                                                ...            
2562             1.0  ...                                                5.0            
1834             1.0  ...                                                0.0            
2206             1.0  ...                                                4.0            
141              1.0  ...                                                6.0            
1231             1.0  ...                                                7.0            

[2115 rows x 4 columns]

Consider four possible models for predicting house prices:

Using only the size and number of rooms.
Using size, number of rooms, and building type.
Using size and building type, and their interaction.
Using a 5-degree polynomial on size, a 5-degree polynomial on number of rooms, and also building type.
Set up a pipeline for each of these four models.

Then, get predictions on the test set for each of your pipelines, and compute the root mean squared error. Which model performed best?

Note: You should only use the function train_test_split() one time in your code; that is, we should be predicting on the same test set for all three models.

In [25]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Preprocess
good_cols = ames.isna().sum() < 100
ames = ames.loc[:, good_cols].dropna()

# Define target and feature columns
target = "SalePrice"
features = ["Gr Liv Area", "TotRms AbvGrd", "Bldg Type"]

X = ames[features]
y = ames[target]

# Perform train/test split once
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Model 1: Using only size and number of rooms
pipeline1 = Pipeline([
    ("scaler", StandardScaler()),
    ("linear_regression", LinearRegression())
])

# Model 2: Using size, number of rooms, and building type
pipeline2 = Pipeline([
    ("preprocessor", ColumnTransformer([
        ("scale_num", StandardScaler(), ["Gr Liv Area", "TotRms AbvGrd"]),
        ("encode_cat", OneHotEncoder(drop="first"), ["Bldg Type"])
    ])),
    ("linear_regression", LinearRegression())
])

# Model 3: Using size and building type, and their interaction
pipeline3 = Pipeline([
    ("preprocessor", ColumnTransformer([
        ("scale_num", StandardScaler(), ["Gr Liv Area"]),
        ("encode_cat", OneHotEncoder(drop="first"), ["Bldg Type"]),
        ("interaction", PolynomialFeatures(interaction_only=True), ["Gr Liv Area"])
    ])),
    ("linear_regression", LinearRegression())
])

# Model 4: Using 5-degree polynomial on size and number of rooms, and building type
pipeline4 = Pipeline([
    ("preprocessor", ColumnTransformer([
        ("poly_features", PolynomialFeatures(degree=5), ["Gr Liv Area", "TotRms AbvGrd"]),
        ("encode_cat", OneHotEncoder(drop="first"), ["Bldg Type"])
    ])),
    ("linear_regression", LinearRegression())
])

# Fit each pipeline and evaluate
pipelines = [pipeline1, pipeline2, pipeline3, pipeline4]
rmse_results = {}

for i, pipeline in enumerate(pipelines, start=1):
    # Fit the pipeline
    pipeline.fit(X_train, y_train)
    # Predict on the test set
    y_pred = pipeline.predict(X_test)
    # Calculate RMSE
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    rmse_results[f"Model {i}"] = rmse

# Display RMSE results
rmse_results

ValueError: could not convert string to float: '1Fam'